package datapath
import chisel3.iotesters.PeekPokeTester
class DecodeTests(c:Decode) extends PeekPokeTester(c){
	poke(c.io.Instruction, 1283)
	poke (c.io.PC, 12)
	poke(c.io.rd_sel, 5)
	poke(c.io.rs1_sel, 16)
	poke(c.io.rs2_sel, 16)
	poke(c.io.writedata, 12)
	poke(c.io.regwrite, 1)
	poke(c.io.rd_sel, 5)
	poke(c.io.rs1_sel, 16)
	poke(c.io.rs2_sel, 16)
	poke(c.io.writedata, 12)
	poke(c.io.regwrite, 1)
	poke(c.io.Immediate,0)
	step(1)
	expect(c.io.Memwrite, 0)
	expect(c.io.Branch1, 0)
	expect(c.io.MemRead, 1)
	expect(c.io.Regwrite, 1)
	expect(c.io.MemtoReg, 1)
	expect(c.io.ALUop, 4)
	expect(c.io.Oper_A_sel, 0)
	expect(c.io.Oper_B_sel, 1)
	expect(c.io.Extend_sel, 0)
	expect(c.io.Next_PC_sel, 0)
	expect(c.io.S_Immediate, 10)
	expect(c.io.SB_Immediate, 22)
	expect(c.io.UJ_Immediate, 12)
	expect(c.io.U_Immediate, 0)
	expect(c.io.I_Immediate, 0)
}
